<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 20px auto; padding: 20px; border: 1px solid #eee; border-radius: 10px; }
        .header { background: #0d6efd; color: #fff; padding: 15px; border-radius: 8px 8px 0 0; text-align: center; }
        .content { padding: 20px; }
        .footer { font-size: 12px; color: #777; text-align: center; margin-top: 20px; }
        .detail-row { margin-bottom: 10px; }
        .label { font-weight: bold; color: #555; }
        .message-box { background: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 4px solid #0d6efd; margin-top: 15px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>New Guest Contact Message</h2>
        </div>
        <div class="content">
            <p>You have received a new message from a guest user on Arewa Smart.</p>
            
            <div class="detail-row">
                <span class="label">Name:</span> {{ $data['name'] }}
            </div>
            <div class="detail-row">
                <span class="label">Email:</span> {{ $data['email'] }}
            </div>
            <div class="detail-row">
                <span class="label">Subject:</span> {{ $data['subject'] }}
            </div>
            
            <div class="message-box">
                <span class="label">Message:</span><br>
                {{ $data['message'] }}
            </div>
        </div>
        <div class="footer">
            This email was automatically generated by Arewa Smart System.
        </div>
    </div>
</body>
</html>
